version: '2.4'

services:
  bitcoind:
    container_name: bitcoind
    hostname: bitcoind
    restart: on-failure
    image: monerobox/bitcoind:latest
    mem_limit: 750m
    memswap_limit: -1
    cpus: 3
    cpuset: "1-3"
    volumes:
      - data_bitcoin:/data/bitcoin
      - settings:/settings
    ports:
      - "8080:8080"
    networks:
      - monerobox

networks:
  monerobox:
    external: true

volumes:
  data_bitcoin:
    external: true
  settings:
    external: true

