version: '2.4'

services:
  manager:
    container_name: manager
    hostname: manager
    restart: always
    image: monerobox/pi4_manager:latest
    mem_limit: 128m
    memswap_limit: -1
    cpus: 1
    cpuset: "0"
    oom_kill_disable: true
    environment:
      - HOST_HOSTNAME
      - HOST_IP
    volumes:
      - /run/docker.sock:/run/docker.sock
      - /usr//bin/docker:/usr/bin/docker
      - settings:/settings
    networks:
      monerobox:
        ipv4_address: 172.20.1.2

volumes:
  settings:
    external: true

networks:
  monerobox:
    external: true
