version: '2.4'

services:
  tor:
    container_name: tor
    hostname: tor
    restart: always
    image: monerobox/tor:latest
    mem_limit: 128m
    memswap_limit: -1
    cpus: 1
    cpuset: "0"
    oom_kill_disable: true
    volumes:
      - settings:/settings
    networks:
      monerobox:
        ipv4_address: 172.20.1.3

volumes:
  settings:
    external: true

networks:
  monerobox:
    external: true
